// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/ratelimit.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RateLimiter_CreateEndpoint_FullMethodName  = "/RateLimiterGRPC.RateLimiter/CreateEndpoint"
	RateLimiter_RequestEndpoint_FullMethodName = "/RateLimiterGRPC.RateLimiter/RequestEndpoint"
)

// RateLimiterClient is the client API for RateLimiter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RateLimiterClient interface {
	CreateEndpoint(ctx context.Context, in *CreateEndpointRQ, opts ...grpc.CallOption) (*CreateEndpointRS, error)
	RequestEndpoint(ctx context.Context, in *RequestEndpointRQ, opts ...grpc.CallOption) (*RequestEndpointRS, error)
}

type rateLimiterClient struct {
	cc grpc.ClientConnInterface
}

func NewRateLimiterClient(cc grpc.ClientConnInterface) RateLimiterClient {
	return &rateLimiterClient{cc}
}

func (c *rateLimiterClient) CreateEndpoint(ctx context.Context, in *CreateEndpointRQ, opts ...grpc.CallOption) (*CreateEndpointRS, error) {
	out := new(CreateEndpointRS)
	err := c.cc.Invoke(ctx, RateLimiter_CreateEndpoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rateLimiterClient) RequestEndpoint(ctx context.Context, in *RequestEndpointRQ, opts ...grpc.CallOption) (*RequestEndpointRS, error) {
	out := new(RequestEndpointRS)
	err := c.cc.Invoke(ctx, RateLimiter_RequestEndpoint_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RateLimiterServer is the server API for RateLimiter service.
// All implementations must embed UnimplementedRateLimiterServer
// for forward compatibility
type RateLimiterServer interface {
	CreateEndpoint(context.Context, *CreateEndpointRQ) (*CreateEndpointRS, error)
	RequestEndpoint(context.Context, *RequestEndpointRQ) (*RequestEndpointRS, error)
	mustEmbedUnimplementedRateLimiterServer()
}

// UnimplementedRateLimiterServer must be embedded to have forward compatible implementations.
type UnimplementedRateLimiterServer struct {
}

func (UnimplementedRateLimiterServer) CreateEndpoint(context.Context, *CreateEndpointRQ) (*CreateEndpointRS, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEndpoint not implemented")
}
func (UnimplementedRateLimiterServer) RequestEndpoint(context.Context, *RequestEndpointRQ) (*RequestEndpointRS, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestEndpoint not implemented")
}
func (UnimplementedRateLimiterServer) mustEmbedUnimplementedRateLimiterServer() {}

// UnsafeRateLimiterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RateLimiterServer will
// result in compilation errors.
type UnsafeRateLimiterServer interface {
	mustEmbedUnimplementedRateLimiterServer()
}

func RegisterRateLimiterServer(s grpc.ServiceRegistrar, srv RateLimiterServer) {
	s.RegisterService(&RateLimiter_ServiceDesc, srv)
}

func _RateLimiter_CreateEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEndpointRQ)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimiterServer).CreateEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimiter_CreateEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimiterServer).CreateEndpoint(ctx, req.(*CreateEndpointRQ))
	}
	return interceptor(ctx, in, info, handler)
}

func _RateLimiter_RequestEndpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestEndpointRQ)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimiterServer).RequestEndpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimiter_RequestEndpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimiterServer).RequestEndpoint(ctx, req.(*RequestEndpointRQ))
	}
	return interceptor(ctx, in, info, handler)
}

// RateLimiter_ServiceDesc is the grpc.ServiceDesc for RateLimiter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RateLimiter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RateLimiterGRPC.RateLimiter",
	HandlerType: (*RateLimiterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEndpoint",
			Handler:    _RateLimiter_CreateEndpoint_Handler,
		},
		{
			MethodName: "RequestEndpoint",
			Handler:    _RateLimiter_RequestEndpoint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ratelimit.proto",
}
