// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: proto/reatelimit.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestEndpointRQ_Method int32

const (
	RequestEndpointRQ_GET    RequestEndpointRQ_Method = 0
	RequestEndpointRQ_POST   RequestEndpointRQ_Method = 1
	RequestEndpointRQ_PUT    RequestEndpointRQ_Method = 2
	RequestEndpointRQ_DELETE RequestEndpointRQ_Method = 3
	RequestEndpointRQ_PATCH  RequestEndpointRQ_Method = 4
)

// Enum value maps for RequestEndpointRQ_Method.
var (
	RequestEndpointRQ_Method_name = map[int32]string{
		0: "GET",
		1: "POST",
		2: "PUT",
		3: "DELETE",
		4: "PATCH",
	}
	RequestEndpointRQ_Method_value = map[string]int32{
		"GET":    0,
		"POST":   1,
		"PUT":    2,
		"DELETE": 3,
		"PATCH":  4,
	}
)

func (x RequestEndpointRQ_Method) Enum() *RequestEndpointRQ_Method {
	p := new(RequestEndpointRQ_Method)
	*p = x
	return p
}

func (x RequestEndpointRQ_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestEndpointRQ_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_reatelimit_proto_enumTypes[0].Descriptor()
}

func (RequestEndpointRQ_Method) Type() protoreflect.EnumType {
	return &file_proto_reatelimit_proto_enumTypes[0]
}

func (x RequestEndpointRQ_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RequestEndpointRQ_Method.Descriptor instead.
func (RequestEndpointRQ_Method) EnumDescriptor() ([]byte, []int) {
	return file_proto_reatelimit_proto_rawDescGZIP(), []int{2, 0}
}

type CreateEndpointRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Path   string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Method string `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Limit  int32  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *CreateEndpointRQ) Reset() {
	*x = CreateEndpointRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reatelimit_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEndpointRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEndpointRQ) ProtoMessage() {}

func (x *CreateEndpointRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reatelimit_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEndpointRQ.ProtoReflect.Descriptor instead.
func (*CreateEndpointRQ) Descriptor() ([]byte, []int) {
	return file_proto_reatelimit_proto_rawDescGZIP(), []int{0}
}

func (x *CreateEndpointRQ) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateEndpointRQ) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateEndpointRQ) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CreateEndpointRQ) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CreateEndpointRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CreateEndpointRS) Reset() {
	*x = CreateEndpointRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reatelimit_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateEndpointRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEndpointRS) ProtoMessage() {}

func (x *CreateEndpointRS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reatelimit_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEndpointRS.ProtoReflect.Descriptor instead.
func (*CreateEndpointRS) Descriptor() ([]byte, []int) {
	return file_proto_reatelimit_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEndpointRS) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RequestEndpointRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method  RequestEndpointRQ_Method `protobuf:"varint,1,opt,name=method,proto3,enum=RateLimiterGRPC.RequestEndpointRQ_Method" json:"method,omitempty"`
	Url     string                   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Body    string                   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Headers string                   `protobuf:"bytes,4,opt,name=headers,proto3" json:"headers,omitempty"`
}

func (x *RequestEndpointRQ) Reset() {
	*x = RequestEndpointRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reatelimit_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestEndpointRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEndpointRQ) ProtoMessage() {}

func (x *RequestEndpointRQ) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reatelimit_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEndpointRQ.ProtoReflect.Descriptor instead.
func (*RequestEndpointRQ) Descriptor() ([]byte, []int) {
	return file_proto_reatelimit_proto_rawDescGZIP(), []int{2}
}

func (x *RequestEndpointRQ) GetMethod() RequestEndpointRQ_Method {
	if x != nil {
		return x.Method
	}
	return RequestEndpointRQ_GET
}

func (x *RequestEndpointRQ) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RequestEndpointRQ) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *RequestEndpointRQ) GetHeaders() string {
	if x != nil {
		return x.Headers
	}
	return ""
}

type RequestEndpointRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestEndpointRS) Reset() {
	*x = RequestEndpointRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_reatelimit_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestEndpointRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEndpointRS) ProtoMessage() {}

func (x *RequestEndpointRS) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reatelimit_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEndpointRS.ProtoReflect.Descriptor instead.
func (*RequestEndpointRS) Descriptor() ([]byte, []int) {
	return file_proto_reatelimit_proto_rawDescGZIP(), []int{3}
}

var File_proto_reatelimit_proto protoreflect.FileDescriptor

var file_proto_reatelimit_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x65, 0x61, 0x74, 0x65, 0x6c, 0x69, 0x6d,
	0x69, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x22, 0x66, 0x0a, 0x10, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x51, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12,
	0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70,
	0x61, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x22, 0x24, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x53, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0xd3, 0x01, 0x0a, 0x11, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x51, 0x12, 0x41, 0x0a,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e,
	0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52,
	0x51, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x22, 0x3b, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x07, 0x0a, 0x03, 0x47, 0x45,
	0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x01, 0x12, 0x07, 0x0a,
	0x03, 0x50, 0x55, 0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45,
	0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x41, 0x54, 0x43, 0x48, 0x10, 0x04, 0x22, 0x13, 0x0a,
	0x11, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x53, 0x32, 0xc0, 0x01, 0x0a, 0x0b, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x65, 0x72, 0x12, 0x56, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x12, 0x21, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x64,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x51, 0x1a, 0x21, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x53, 0x12, 0x59, 0x0a, 0x0f, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x22, 0x2e,
	0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52,
	0x51, 0x1a, 0x22, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x47,
	0x52, 0x50, 0x43, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x53, 0x42, 0x27, 0x5a, 0x25, 0x69, 0x6f, 0x2f, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2f, 0x70, 0x61, 0x62, 0x6c, 0x6f, 0x75, 0x62, 0x61, 0x6c, 0x2f, 0x72, 0x61, 0x74,
	0x65, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_reatelimit_proto_rawDescOnce sync.Once
	file_proto_reatelimit_proto_rawDescData = file_proto_reatelimit_proto_rawDesc
)

func file_proto_reatelimit_proto_rawDescGZIP() []byte {
	file_proto_reatelimit_proto_rawDescOnce.Do(func() {
		file_proto_reatelimit_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_reatelimit_proto_rawDescData)
	})
	return file_proto_reatelimit_proto_rawDescData
}

var file_proto_reatelimit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_reatelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_reatelimit_proto_goTypes = []interface{}{
	(RequestEndpointRQ_Method)(0), // 0: RateLimiterGRPC.RequestEndpointRQ.Method
	(*CreateEndpointRQ)(nil),      // 1: RateLimiterGRPC.CreateEndpointRQ
	(*CreateEndpointRS)(nil),      // 2: RateLimiterGRPC.CreateEndpointRS
	(*RequestEndpointRQ)(nil),     // 3: RateLimiterGRPC.RequestEndpointRQ
	(*RequestEndpointRS)(nil),     // 4: RateLimiterGRPC.RequestEndpointRS
}
var file_proto_reatelimit_proto_depIdxs = []int32{
	0, // 0: RateLimiterGRPC.RequestEndpointRQ.method:type_name -> RateLimiterGRPC.RequestEndpointRQ.Method
	1, // 1: RateLimiterGRPC.RateLimiter.CreateEndpoint:input_type -> RateLimiterGRPC.CreateEndpointRQ
	3, // 2: RateLimiterGRPC.RateLimiter.RequestEndpoint:input_type -> RateLimiterGRPC.RequestEndpointRQ
	2, // 3: RateLimiterGRPC.RateLimiter.CreateEndpoint:output_type -> RateLimiterGRPC.CreateEndpointRS
	4, // 4: RateLimiterGRPC.RateLimiter.RequestEndpoint:output_type -> RateLimiterGRPC.RequestEndpointRS
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_reatelimit_proto_init() }
func file_proto_reatelimit_proto_init() {
	if File_proto_reatelimit_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_reatelimit_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEndpointRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reatelimit_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateEndpointRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reatelimit_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestEndpointRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_reatelimit_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestEndpointRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_reatelimit_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reatelimit_proto_goTypes,
		DependencyIndexes: file_proto_reatelimit_proto_depIdxs,
		EnumInfos:         file_proto_reatelimit_proto_enumTypes,
		MessageInfos:      file_proto_reatelimit_proto_msgTypes,
	}.Build()
	File_proto_reatelimit_proto = out.File
	file_proto_reatelimit_proto_rawDesc = nil
	file_proto_reatelimit_proto_goTypes = nil
	file_proto_reatelimit_proto_depIdxs = nil
}
